modLoader="javafml"
loaderVersion="[38,)"
license="MIT License https://github.com/BuiltBrokenModding/SBM-Growmeal/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Growmeal/issues"

[[mods]]
	modId="sbmgrowmeal"
	version="${file.jarVersion}"
	displayName="Growmeal"
	description='''Instantly grow plants'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/sbm-growmeal"
	authors="bl4ckscor3"

[[dependencies.sbmgrowmeal]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmgrowmeal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"