modLoader="javafml"
loaderVersion="[46,)"
license="MIT License https://github.com/bl4ckscor3/Growmeal/blob/1.20/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/Growmeal/issues"

[[mods]]
	modId="sbmgrowmeal"
	version="${file.jarVersion}"
	displayName="Growmeal"
	description='''Instantly grow plants'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/growmeal"
	authors="bl4ckscor3"

[[dependencies.sbmgrowmeal]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmgrowmeal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"