modLoader="javafml"
loaderVersion="[1,)"
license="MIT License https://github.com/bl4ckscor3/Growmeal/blob/1.21/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/Growmeal/issues"

[[mods]]
	modId="sbmgrowmeal"
	version="${file.jarVersion}"
	displayName="Growmeal"
	description='''Instantly grow plants'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/growmeal"
	authors="bl4ckscor3"

[[dependencies.sbmgrowmeal]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.76-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmgrowmeal]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"